# Generated by Django 2.1 on 2018-08-17 19:08

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('local_score', models.IntegerField(blank=True, null=True)),
                ('visitor_score', models.IntegerField(blank=True, null=True)),
                ('match_state', models.IntegerField(choices=[(0, 'new'), (1, 'playing'), (2, 'local'), (3, 'parity'), (4, 'visitor')], default=0)),
                ('local_factor', models.FloatField()),
                ('parity_factor', models.FloatField()),
                ('visitor_factor', models.FloatField()),
                ('start_datetime', models.DateTimeField()),
                ('ent_datetime', models.DateTimeField()),
            ],
            options={
                'abstract': False,
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=250)),
                ('factor', models.FloatField(blank=True, null=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football.League')),
            ],
            options={
                'abstract': False,
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
            },
        ),
        migrations.AddField(
            model_name='match',
            name='local_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_team', to='football.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='visitor_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Team'),
        ),
    ]
