# Generated by Django 5.2.2 on 2025-07-23 03:30

import django.db.models.deletion
import django_countries.fields
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("draw_percentage", models.FloatField(blank=True, null=True)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LeagueRelatedName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "bet_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.betpage",
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="football.league",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "league",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="football.league",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "local_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "visitor_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("N", "new"),
                            ("U", "used"),
                            ("P", "playing"),
                            ("L", "local"),
                            ("R", "draw"),
                            ("V", "visitor"),
                            ("T", "not used"),
                        ],
                        default="N",
                        max_length=1,
                    ),
                ),
                ("local_factor", models.FloatField()),
                ("draw_factor", models.FloatField()),
                ("visitor_factor", models.FloatField()),
                ("start_datetime", models.DateTimeField()),
                ("score", models.FloatField(default=0)),
                (
                    "local_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_team",
                        to="football.team",
                    ),
                ),
                (
                    "visitor_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="football.team"
                    ),
                ),
            ],
            options={
                "verbose_name": "match",
                "verbose_name_plural": "matches",
            },
        ),
    ]
