# Generated by Django 5.2.2 on 2026-08-25 21:40

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import django_extensions.db.fields
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


def create_sources(apps, schema_editor):
    source = apps.get_model("football", "Source")
    source.objects.get_or_create(
        code="api_football",
        defaults={
            "name": "API-Football",
            "base_url": "https://v3.football.api-sports.io/",
        },
    )
    source.objects.get_or_create(
        code="inkabet",
        defaults={
            "name": "Inkabet",
            "base_url": "https://d-cf.inkabetplayground.net/api/sb/v1/",
        },
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name="Bookmaker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("external_id", models.CharField(max_length=150)),
                ("name", models.CharField(max_length=250)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="OddsMarket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("external_id", models.CharField(max_length=150)),
                ("name", models.CharField(max_length=250)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("base_url", models.URLField()),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("competition_type", models.CharField(max_length=50)),
                (
                    "country",
                    django_countries.fields.CountryField(blank=True, max_length=2),
                ),
                ("enabled", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("country", "name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country", "name", "competition_type"),
                        name="football_competition_country_name_type_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("coverage", models.JSONField(blank=True, default=dict)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="football.competition",
                    ),
                ),
            ],
            options={
                "ordering": ("competition", "-year"),
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("kickoff", models.DateTimeField()),
                ("kickoff_timezone", models.CharField(blank=True, max_length=50)),
                ("status_short", models.CharField(max_length=10)),
                ("status_long", models.CharField(max_length=100)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[("HOME", "Home"), ("DRAW", "Draw"), ("AWAY", "Away")],
                        max_length=4,
                    ),
                ),
                ("home_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("away_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "halftime_home_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "halftime_away_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "fulltime_home_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "fulltime_away_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "extratime_home_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "extratime_away_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "penalties_home_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "penalties_away_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "observed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches",
                        to="football.season",
                    ),
                ),
            ],
            options={
                "ordering": ("-kickoff",),
            },
        ),
        migrations.CreateModel(
            name="OddsSnapshot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("home", models.DecimalField(decimal_places=4, max_digits=10)),
                ("draw", models.DecimalField(decimal_places=4, max_digits=10)),
                ("away", models.DecimalField(decimal_places=4, max_digits=10)),
                ("provider_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "observed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "bookmaker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="odds",
                        to="football.bookmaker",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="odds",
                        to="football.oddsmarket",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odds",
                        to="football.match",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="odds",
                        to="football.source",
                    ),
                ),
            ],
            options={
                "ordering": ("-observed_at",),
            },
        ),
        migrations.AddField(
            model_name="oddsmarket",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="football.source"
            ),
        ),
        migrations.CreateModel(
            name="MatchSourceRef",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=150)),
                ("external_label", models.CharField(blank=True, max_length=250)),
                (
                    "reconciliation_status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("RESOLVED", "Resolved")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_refs",
                        to="football.match",
                    ),
                ),
                (
                    "proposed_match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposed_source_refs",
                        to="football.match",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_refs",
                        to="football.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompetitionSourceRef",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=150)),
                ("external_name", models.CharField(blank=True, max_length=250)),
                (
                    "reconciliation_status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("RESOLVED", "Resolved")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("external_slug", models.CharField(blank=True, max_length=300)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "competition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_refs",
                        to="football.competition",
                    ),
                ),
                (
                    "proposed_competition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposed_source_refs",
                        to="football.competition",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competition_refs",
                        to="football.source",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bookmaker",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="football.source"
            ),
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("code", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teams",
                        to="football.competition",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="match",
            name="away_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="away_matches",
                to="football.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="home_matches",
                to="football.team",
            ),
        ),
        migrations.CreateModel(
            name="TeamSourceRef",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=150)),
                ("external_name", models.CharField(blank=True, max_length=250)),
                (
                    "reconciliation_status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("RESOLVED", "Resolved")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_source_refs",
                        to="football.competition",
                    ),
                ),
                (
                    "proposed_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposed_source_refs",
                        to="football.team",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_refs",
                        to="football.source",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_refs",
                        to="football.team",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="season",
            constraint=models.UniqueConstraint(
                fields=("competition", "year"),
                name="football_season_competition_year_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="oddssnapshot",
            constraint=models.UniqueConstraint(
                fields=("match", "source", "bookmaker", "market"),
                name="football_odds_current_value_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="oddsmarket",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"),
                name="football_market_source_external_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchsourceref",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"),
                name="football_match_ref_source_external_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchsourceref",
            constraint=models.UniqueConstraint(
                condition=models.Q(("match__isnull", False)),
                fields=("source", "match"),
                name="football_match_ref_source_canonical_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="competitionsourceref",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"),
                name="football_competition_ref_source_external_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="competitionsourceref",
            constraint=models.UniqueConstraint(
                condition=models.Q(("competition__isnull", False)),
                fields=("source", "competition"),
                name="football_competition_ref_source_canonical_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmaker",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"),
                name="football_bookmaker_source_external_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("competition", "name"),
                name="football_team_competition_name_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                fields=("season", "home_team", "away_team", "kickoff"),
                name="football_match_canonical_identity_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.CheckConstraint(
                condition=models.Q(("home_team", models.F("away_team")), _negated=True),
                name="football_match_distinct_teams",
            ),
        ),
        migrations.AddConstraint(
            model_name="teamsourceref",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"),
                name="football_team_ref_source_external_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="teamsourceref",
            constraint=models.UniqueConstraint(
                condition=models.Q(("team__isnull", False)),
                fields=("source", "team"),
                name="football_team_ref_source_canonical_unique",
            ),
        ),
        migrations.RunPython(create_sources, migrations.RunPython.noop),
    ]
