# Generated by Django 5.2.2 on 2025-07-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="inkabet_url",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
