# Generated by Django 2.1 on 2018-08-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_state',
            field=models.IntegerField(choices=[(0, 'new'), (1, 'used'), (2, 'playing'), (3, 'local'), (4, 'parity'), (5, 'visitor')], default=0),
        ),
    ]
