# Generated by Django 2.1 on 2018-08-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_auto_20180820_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='ent_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
