# Generated by Django 5.2.2 on 2025-09-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0002_match_inkabet_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="name_en",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="league",
            name="name_local",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
