# Generated by Django 5.2.2 on 2026-08-27 17:46

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0002_oddsobservation_predictionexperiment_prediction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapitalExperiment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("source_model_code", models.CharField(blank=True, max_length=30)),
                ("source_model_variant", models.CharField(blank=True, max_length=20)),
                ("source_comparator_code", models.CharField(blank=True, max_length=30)),
                ("decision_policy_code", models.CharField(max_length=30)),
                (
                    "decision_policy_variant",
                    models.CharField(blank=True, max_length=30),
                ),
                ("engine_version", models.CharField(default="fs004-v1", max_length=50)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("REPLAY", "Deterministic replay"),
                            ("MONTE_CARLO", "Monte Carlo"),
                            ("STRESS", "Stress"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "initial_bankroll",
                    models.DecimalField(decimal_places=8, max_digits=24),
                ),
                ("config", models.JSONField(default=dict)),
                ("input_count", models.PositiveIntegerField(default=0)),
                ("input_hash", models.CharField(max_length=64)),
                ("input_manifest", models.JSONField(default=dict)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.JSONField(blank=True, default=dict)),
                (
                    "source_experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_experiments",
                        to="football.predictionexperiment",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("source_comparator_code__gt", ""),
                                ("source_model_code", ""),
                            ),
                            models.Q(
                                ("source_comparator_code", ""),
                                ("source_model_code__gt", ""),
                            ),
                            _connector="OR",
                        ),
                        name="football_capital_experiment_one_source_identity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("initial_bankroll__gt", 0)),
                        name="football_capital_experiment_positive_bankroll",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CapitalPolicyRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("policy_code", models.CharField(max_length=40)),
                ("policy_version", models.CharField(max_length=100)),
                ("policy_config", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRODUCED", "Produced"),
                            ("UNAVAILABLE", "Unavailable"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=12,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=120)),
                ("seed", models.BigIntegerField(blank=True, null=True)),
                ("path_count", models.PositiveIntegerField(blank=True, null=True)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_runs",
                        to="football.capitalexperiment",
                    ),
                ),
            ],
            options={
                "ordering": ("experiment_id", "id"),
            },
        ),
        migrations.CreateModel(
            name="CapitalLedgerEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_time", models.DateTimeField()),
                ("batch_index", models.PositiveIntegerField()),
                ("step", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "requested_stake",
                    models.DecimalField(decimal_places=8, max_digits=24),
                ),
                ("applied_stake", models.DecimalField(decimal_places=8, max_digits=24)),
                (
                    "bankroll_before",
                    models.DecimalField(decimal_places=8, max_digits=24),
                ),
                (
                    "bankroll_after",
                    models.DecimalField(decimal_places=8, max_digits=24),
                ),
                ("profit_loss", models.DecimalField(decimal_places=8, max_digits=24)),
                ("action_snapshot", models.CharField(max_length=6)),
                ("outcome_snapshot", models.CharField(blank=True, max_length=4)),
                (
                    "price_snapshot",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("capital_reason", models.CharField(blank=True, max_length=120)),
                ("policy_state", models.JSONField(blank=True, default=dict)),
                ("cap_hit", models.BooleanField(default=False)),
                (
                    "shortfall",
                    models.DecimalField(decimal_places=8, default=0, max_digits=24),
                ),
                ("practical_ruin", models.BooleanField(default=False)),
                ("termination_reason", models.CharField(blank=True, max_length=120)),
                (
                    "source_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_ledger_entries",
                        to="football.decision",
                    ),
                ),
                (
                    "policy_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="football.capitalpolicyrun",
                    ),
                ),
            ],
            options={
                "ordering": ("policy_run_id", "batch_index", "source_decision_id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy_run", "source_decision"),
                        name="football_capital_ledger_run_decision_unique",
                    )
                ],
            },
        ),
    ]
