# Generated by Django 2.1 on 2018-08-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_auto_20180820_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_state',
            field=models.IntegerField(choices=[(0, 'new'), (1, 'used'), (2, 'playing'), (3, 'local'), (4, 'parity'), (5, 'visitor'), (6, 'unknow')], default=0),
        ),
    ]
