# Generated by Django 5.2.2 on 2025-09-07 15:24

from django.db import migrations


def update_leagues(apps, schema_editor):
    League = apps.get_model("football", "League")
    League.objects.all().delete()

    leagues_data = [
        {
            "country": "ES",
            "name": "LaLiga",
            "name_en": "LaLiga",
            "name_local": "LaLiga Santander"
        },
        {
            "country": "GB",
            "name": "Premier League",
            "name_en": "Premier League",
            "name_local": "Premier League"
        },
        {
            "country": "IT",
            "name": "Serie A",
            "name_en": "Serie A",
            "name_local": "Serie A TIM"
        },
        {
            "country": "DE",
            "name": "Bundesliga",
            "name_en": "Bundesliga",
            "name_local": "Fußball-Bundesliga"
        },
        {
            "country": "FR",
            "name": "Ligue 1",
            "name_en": "Ligue 1",
            "name_local": "Ligue 1 Uber Eats"
        },
        {
            "country": "PT",
            "name": "Primeira Liga",
            "name_en": "Primeira Liga",
            "name_local": "Liga Portugal Betclic"
        },
        {
            "country": "NL",
            "name": "Eredivisie",
            "name_en": "Eredivisie",
            "name_local": "Eredivisie"
        },
        {
            "country": "BE",
            "name": "Pro League",
            "name_en": "Belgian Pro League",
            "name_local": "Jupiler League"
        },
        {
            "country": "TR",
            "name": "Superliga",
            "name_en": "Süper Lig",
            "name_local": "Süper Lig"
        },
        {
            "country": "GR",
            "name": "Super Liga",
            "name_en": "Super League",
            "name_local": "Σούπερ Λιγκ Ελλάδα"
        },
        {
            "country": "GB-SCT",
            "name": "Premier League",
            "name_en": "Premiership",
            "name_local": "Scottish Premiership"
        },
        {
            "country": "CH",
            "name": "Super Liga",
            "name_en": "Swiss Super League",
            "name_local": "Credit Suisse Super League"
        },
        {
            "country": "AT",
            "name": "Bundesliga",
            "name_en": "Bundesliga",
            "name_local": "Österreichische Fußball-Bundesliga"
        },
        {
            "country": "SE",
            "name": "Allsvenskan",
            "name_en": "Allsvenskan",
            "name_local": "Allsvenskan"
        },
        {
            "country": "NO",
            "name": "Tippeligaen",
            "name_en": "Eliteserien",
            "name_local": "Eliteserien"
        },
        {
            "country": "DK",
            "name": "Superliga",
            "name_en": "Superliga",
            "name_local": "Superligaen"
        },
        {
            "country": "PL",
            "name": "Ekstraklasa",
            "name_en": "Ekstraklasa",
            "name_local": "PKO Ekstraklasa"
        },
        {
            "country": "RO",
            "name": "Liga I",
            "name_en": "Liga I",
            "name_local": "SuperLiga României"
        },
        {
            "country": "RS",
            "name": "SuperLiga",
            "name_en": "Super Liga",
            "name_local": "Суперлига Србије"
        },
        {
            "country": "HR",
            "name": "HNL",
            "name_en": "Croatian First Football League",
            "name_local": "SuperSport HNL"
        },
        {
            "country": "AR",
            "name": "Liga Profesional",
            "name_en": "Primera División",
            "name_local": "Liga Profesional de Fútbol"
        },
        {
            "country": "BR",
            "name": "Serie A",
            "name_en": "Campeonato Brasileiro Série A",
            "name_local": "Brasileirão Série A"
        },
        {
            "country": "UY",
            "name": "Primera División",
            "name_en": "Uruguayan Primera División",
            "name_local": "Campeonato Uruguayo"
        },
        {
            "country": "CL",
            "name": "Liga de primera",
            "name_en": "Primera División",
            "name_local": "Campeonato Nacional AFP PlanVital"
        },
        {
            "country": "CO",
            "name": "Primera A",
            "name_en": "Categoría Primera A",
            "name_local": "Liga BetPlay Dimayor"
        },
        {
            "country": "PE",
            "name": "Liga 1",
            "name_en": "Peruvian Liga 1",
            "name_local": "Liga 1 Betsson"
        },
        {
            "country": "PY",
            "name": "Primera División",
            "name_en": "División Profesional",
            "name_local": "Liga Paraguaya de Fútbol"
        },
        {
            "country": "EC",
            "name": "LigaPro",
            "name_en": "Serie A",
            "name_local": "LigaPro Serie A"
        },
        {
            "country": "MX",
            "name": "Liga MX",
            "name_en": "Liga MX",
            "name_local": "Liga BBVA MX"
        },
        {
            "country": "US",
            "name": "MLS",
            "name_en": "Major League Soccer",
            "name_local": "MLS"
        },
        {
            "country": "CA",
            "name": "CPL",
            "name_en": "Premier League",
            "name_local": "Canadian Premier League"
        },
        {
            "country": "CR",
            "name": "Primera División",
            "name_en": "Liga FPD",
            "name_local": "Liga Promerica"
        },
        {
            "country": "EG",
            "name": "Liga Premier",
            "name_en": "Premier League",
            "name_local": "الدوري المصري الممتاز"
        },
        {
            "country": "SA",
            "name": "ProLeague",
            "name_en": "Saudi Professional League",
            "name_local": "دوري المحترفين السعودي"
        },
        {
            "country": "QA",
            "name": "Stars League",
            "name_en": "Stars League",
            "name_local": "دوري نجوم قطر"
        },
        {
            "country": "JP",
            "name": "J1 League",
            "name_en": "J1 League",
            "name_local": "明治安田生命J1リーグ"
        },
        {
            "country": "CN",
            "name": "Super Liga China",
            "name_en": "Super League",
            "name_local": "中国足球超级联赛"
        },
        {
            "country": "KR",
            "name": "K League 1",
            "name_en": "K-League 1",
            "name_local": "K리그1"
        },
        {
            "country": "BO",
            "name": "Primera División",
            "name_en": "Primera División",
            "name_local": "División Profesional"
        },
        {
            "country": "BA",
            "name": "Liga Premier",
            "name_en": "Premier League",
            "name_local": "Premijer Liga Bosne i Hercegovine"
        },
        {
            "country": "CY",
            "name": "1ª División",
            "name_en": "1st Division",
            "name_local": "Πρωτάθλημα Κατηγορίας Κύπρου"
        },
        {
            "country": "SV",
            "name": "Primera División",
            "name_en": "Primera División",
            "name_local": "Primera División de Fútbol de El Salvador"
        },
        {
            "country": "EE",
            "name": "Meistriliiga",
            "name_en": "Meistriliiga",
            "name_local": "Meistriliiga"
        },
        {
            "country": "GT",
            "name": "Liga Nacional",
            "name_en": "Liga Nacional",
            "name_local": "Liga Nacional de Fútbol de Guatemala"
        },
        {
            "country": "GB-NIR",
            "name": "Premier de Irlanda",
            "name_en": "League of Ireland Premier Division",
            "name_local": "NIFL Premiership"
        },
        {
            "country": "JM",
            "name": "Premier League",
            "name_en": "Premier League",
            "name_local": "Jamaica Premier League"
        },
        {
            "country": "LV",
            "name": "Virsliga",
            "name_en": "Virsliga",
            "name_local": "Latvijas Virslīga"
        },
        {
            "country": "LT",
            "name": "A Lyga",
            "name_en": "A Lyga",
            "name_local": "A Lyga"
        },
        {
            "country": "PA",
            "name": "LPF",
            "name_en": "LPF",
            "name_local": "Liga Panameña de Fútbol"
        },
        {
            "country": "TH",
            "name": "Liga 1",
            "name_en": "Thai League",
            "name_local": "ไทยลีก 1"
        }
    ]
    leagues = [League(**data) for data in leagues_data]
    League.objects.bulk_create(leagues)


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0003_league_name_en_league_name_local"),
    ]

    operations = [
        migrations.RunPython(update_leagues, reverse_code=migrations.RunPython.noop)
    ]
