# Generated by Django 5.2.2 on 2026-08-28 16:47

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0003_capitalexperiment_capitalpolicyrun_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaptureRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("SCHEDULER", "Scheduler")],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                            ("NO_WORK", "No work"),
                            ("CONCURRENT_EXECUTOR", "Concurrent executor"),
                        ],
                        default="RUNNING",
                        max_length=24,
                    ),
                ),
                ("planning_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("config_snapshot", models.JSONField(default=dict)),
                ("quota_basis", models.CharField(blank=True, max_length=40)),
                ("quota_limit", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "quota_remaining_before",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "quota_remaining_after",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("quota_observed_at", models.DateTimeField(blank=True, null=True)),
                ("mandatory_reserve", models.PositiveIntegerField(default=0)),
                ("provider_attempts", models.PositiveIntegerField(default=0)),
                ("provider_pages", models.PositiveIntegerField(default=0)),
                ("provider_retries", models.PositiveIntegerField(default=0)),
                ("observations_created", models.PositiveIntegerField(default=0)),
                ("snapshots_changed", models.PositiveIntegerField(default=0)),
                ("fixtures_changed", models.PositiveIntegerField(default=0)),
                ("matches_resolved", models.PositiveIntegerField(default=0)),
                ("skips", models.PositiveIntegerField(default=0)),
                ("failures", models.PositiveIntegerField(default=0)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("error_class", models.CharField(blank=True, max_length=120)),
                ("error_message", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ("-started_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="CaptureWorkItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("ODDS_CAPTURE", "Odds capture"),
                            ("FIXTURE_REFRESH", "Fixture refresh"),
                            ("RESULT_REFRESH", "Result refresh"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("NOT_DUE", "Not due"),
                            ("ALREADY_FULFILLED", "Already fulfilled"),
                            ("STATUS_INELIGIBLE", "Status ineligible"),
                            ("ODDS_NOT_COVERED", "Odds not covered"),
                            ("UNRESOLVED_IDENTITY", "Unresolved identity"),
                            ("QUOTA_RESERVE", "Quota reserve"),
                            (
                                "INSUFFICIENT_WORST_CASE_BUDGET",
                                "Insufficient worst-case budget",
                            ),
                            ("MISSED_WINDOW", "Missed window"),
                            ("LATE_CAPTURE", "Late capture"),
                            ("PROVIDER_BACKOFF", "Provider backoff"),
                            ("CONCURRENT_EXECUTOR", "Concurrent executor"),
                            ("SUCCESS", "Success"),
                            ("SUCCESS_EMPTY", "Success empty"),
                            ("PARTIAL_PAGINATION", "Partial pagination"),
                            ("FAILED_PROVIDER", "Provider failed"),
                        ],
                        default="PLANNED",
                        max_length=40,
                    ),
                ),
                ("logical_identity", models.CharField(max_length=500)),
                ("intended_window", models.CharField(blank=True, max_length=80)),
                ("target_at", models.DateTimeField(blank=True, null=True)),
                ("not_before", models.DateTimeField(blank=True, null=True)),
                ("not_after", models.DateTimeField(blank=True, null=True)),
                ("priority", models.PositiveIntegerField(default=0)),
                ("reason", models.CharField(blank=True, max_length=120)),
                ("estimated_min_cost", models.PositiveIntegerField(default=0)),
                ("estimated_max_cost", models.PositiveIntegerField(default=0)),
                ("actual_attempts", models.PositiveIntegerField(default=0)),
                ("actual_pages", models.PositiveIntegerField(default=0)),
                ("actual_retries", models.PositiveIntegerField(default=0)),
                ("observations_created", models.PositiveIntegerField(default=0)),
                ("snapshots_changed", models.PositiveIntegerField(default=0)),
                ("fixtures_changed", models.PositiveIntegerField(default=0)),
                ("matches_resolved", models.PositiveIntegerField(default=0)),
                ("quota_before", models.JSONField(blank=True, default=dict)),
                ("quota_after", models.JSONField(blank=True, default=dict)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("lateness_seconds", models.IntegerField(blank=True, null=True)),
                ("error_class", models.CharField(blank=True, max_length=120)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                (
                    "market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capture_work_items",
                        to="football.oddsmarket",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capture_work_items",
                        to="football.match",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_items",
                        to="football.capturerun",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capture_work_items",
                        to="football.source",
                    ),
                ),
            ],
            options={
                "ordering": ("run_id", "priority", "id"),
                "indexes": [
                    models.Index(
                        fields=["purpose", "status", "target_at"],
                        name="football_capture_due_idx",
                    ),
                    models.Index(
                        fields=["logical_identity", "status"],
                        name="football_capture_identity_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ("SUCCESS", "SUCCESS_EMPTY", "LATE_CAPTURE"))
                        ),
                        fields=("logical_identity",),
                        name="football_capture_fulfilled_identity_unique",
                    )
                ],
            },
        ),
    ]
