# Generated by Django 5.2.2 on 2026-08-28

import uuid

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0004_capturerun_captureworkitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="capitalexperiment",
            name="logical_identity",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="predictionexperiment",
            name="intended_window",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="predictionexperiment",
            name="logical_identity",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="predictionexperiment",
            name="target_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "cycle_identity",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("SCHEDULER", "Scheduler")],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("NO_WORK", "No work"),
                            ("DEGRADED", "Degraded"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=12,
                    ),
                ),
                ("planning_at", models.DateTimeField()),
                ("local_day", models.DateField()),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("phase_states", models.JSONField(blank=True, default=dict)),
                ("capture_run_ids", models.JSONField(blank=True, default=list)),
                (
                    "prediction_experiment_ids",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "capital_experiment_ids",
                    models.JSONField(blank=True, default=list),
                ),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("config_snapshot", models.JSONField(blank=True, default=dict)),
                ("report", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("-started_at", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="predictionexperiment",
            constraint=models.UniqueConstraint(
                condition=models.Q(mode="PROSPECTIVE") & ~models.Q(logical_identity=""),
                fields=("competition", "logical_identity"),
                name="football_prospective_identity_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="capitalexperiment",
            constraint=models.UniqueConstraint(
                condition=~models.Q(logical_identity=""),
                fields=("logical_identity",),
                name="football_capital_logical_identity_unique",
            ),
        ),
    ]
