# Generated by Django 2.1 on 2018-08-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_auto_20180822_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='local_factor_half_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='local_score_half_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_state_half_time',
            field=models.IntegerField(choices=[(0, 'new'), (1, 'used'), (2, 'playing'), (3, 'local'), (4, 'parity'), (5, 'visitor'), (6, 'unknow')], default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='parity_factor_half_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='visitor_factor_half_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='visitor_score_half_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
