# Generated by Django 2.1 on 2018-09-24 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_auto_20180912_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueRelatedName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_name', models.CharField(max_length=250)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.League')),
            ],
        ),
    ]
