# Generated by Django 2.1 on 2018-10-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_leaguerelatedname'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='country',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
