# Generated by Django 2.1 on 2018-12-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_league_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_state',
            field=models.IntegerField(choices=[(0, 'new'), (1, 'used'), (2, 'playing'), (3, 'local'), (4, 'parity'), (5, 'visitor'), (6, 'unknow'), (7, 'favorite'), (8, 'not used')], default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_state_half_time',
            field=models.IntegerField(choices=[(0, 'new'), (1, 'used'), (2, 'playing'), (3, 'local'), (4, 'parity'), (5, 'visitor'), (6, 'unknow'), (7, 'favorite'), (8, 'not used')], default=0),
        ),
    ]
