# Generated by Django 2.1.5 on 2019-01-12 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_auto_20181226_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='local_factor_half_time',
        ),
        migrations.RemoveField(
            model_name='match',
            name='local_score_half_time',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_state_half_time',
        ),
        migrations.RemoveField(
            model_name='match',
            name='parity_factor_half_time',
        ),
        migrations.RemoveField(
            model_name='match',
            name='visitor_factor_half_time',
        ),
        migrations.RemoveField(
            model_name='match',
            name='visitor_score_half_time',
        ),
    ]
