# Generated by Django 2.1.5 on 2019-01-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_auto_20190111_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_state',
        ),
        migrations.AddField(
            model_name='match',
            name='state',
            field=models.CharField(choices=[('N', 'new'), ('U', 'used'), ('P', 'playing'), ('L', 'local'), ('R', 'parity'), ('V', 'visitor'), ('U', 'unknow'), ('T', 'not used')], default='N', max_length=1),
        ),
    ]
