# Generated by Django 5.2.17 on 2026-09-08 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "football",
            "0010_prediction_bet_eligible_prediction_evidence_identity_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dixoncolesreadinessprofile",
            name="football_dc_readiness_profile_version_unique",
        ),
        migrations.RemoveConstraint(
            model_name="dixoncolesreadinessprofile",
            name="football_dc_readiness_profile_active_unique",
        ),
        migrations.AddField(
            model_name="dixoncolesreadinessprofile",
            name="basis_identity",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="dixoncolesreadinessprofile",
            name="calibration_strategy_version",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="dixoncolesreadinessprofile",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dixoncolesreadinessprofile",
            name="disposition",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="dixoncolesreadinessprofile",
            name="evidence",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="dixoncolesreadinessprofile",
            name="model_code",
            field=models.CharField(default="DIXON_COLES", max_length=30),
        ),
        migrations.AddField(
            model_name="dixoncolesreadinessprofile",
            name="profile_rule_version",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="dixoncolesreadinessprofile",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="successors",
                to="football.dixoncolesreadinessprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="dixoncolesreadinessprofile",
            constraint=models.UniqueConstraint(
                fields=("competition", "model_code", "version"),
                name="football_dc_readiness_profile_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="dixoncolesreadinessprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("competition", "model_code"),
                name="football_dc_readiness_profile_active_unique",
            ),
        ),
    ]
