# Generated by Django 5.2.17 on 2026-09-09 01:35

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models

BOOKMAKER_MAPPINGS = {
    ("api_football", "1"): ("10bet", "10Bet"),
    ("api_football", "2"): ("marathonbet", "Marathonbet"),
    ("api_football", "3"): ("betfair", "Betfair"),
    ("api_football", "4"): ("pinnacle", "Pinnacle"),
    ("api_football", "5"): ("sbo", "SBO"),
    ("api_football", "7"): ("william-hill", "William Hill"),
    ("api_football", "8"): ("bet365", "Bet365"),
    ("api_football", "9"): ("dafabet", "Dafabet"),
    ("api_football", "11"): ("1xbet", "1xBet"),
    ("api_football", "16"): ("unibet", "Unibet"),
    ("api_football", "21"): ("888sport", "888Sport"),
    ("api_football", "32"): ("betano", "Betano"),
    ("api_football", "34"): ("superbet", "Superbet"),
    ("api_football", "36"): ("betvictor", "BetVictor"),
    ("inkabet", "inkabet"): ("inkabet", "Inkabet"),
}
MARKET_MAPPINGS = {
    ("api_football", "1"): ("1x2", "1X2"),
    ("inkabet", "MW3W"): ("1x2", "1X2"),
}


def seed_governed_market_identities(apps, schema_editor):
    del schema_editor
    Bookmaker = apps.get_model("football", "Bookmaker")
    BookmakerCanonicalRef = apps.get_model("football", "BookmakerCanonicalRef")
    CanonicalBookmaker = apps.get_model("football", "CanonicalBookmaker")
    OddsMarket = apps.get_model("football", "OddsMarket")
    OddsMarketCanonicalRef = apps.get_model("football", "OddsMarketCanonicalRef")
    CanonicalOddsMarket = apps.get_model("football", "CanonicalOddsMarket")
    common = {
        "mapping_version": "fs013-governed-v1",
        "reason": "UNMAPPED_SOURCE_EXTERNAL_ID",
    }
    for bookmaker in Bookmaker.objects.select_related("source"):
        mapping = BOOKMAKER_MAPPINGS.get(
            (bookmaker.source.code, str(bookmaker.external_id))
        )
        defaults = {
            **common,
            "reconciliation_status": "PENDING",
            "context": {
                "authority": "governed_source_external_id_registry",
                "raw_name": bookmaker.name,
            },
        }
        if mapping:
            canonical, _ = CanonicalBookmaker.objects.get_or_create(
                code=mapping[0], defaults={"name": mapping[1]}
            )
            defaults.update(
                canonical_bookmaker=canonical,
                reconciliation_status="RESOLVED",
                reason="GOVERNED_MAPPING",
            )
        BookmakerCanonicalRef.objects.update_or_create(
            bookmaker=bookmaker, defaults=defaults
        )
    for market in OddsMarket.objects.select_related("source"):
        mapping = MARKET_MAPPINGS.get((market.source.code, str(market.external_id)))
        defaults = {
            **common,
            "reconciliation_status": "PENDING",
            "context": {
                "authority": "governed_source_external_id_registry",
                "raw_name": market.name,
            },
        }
        if mapping:
            canonical, _ = CanonicalOddsMarket.objects.get_or_create(
                code=mapping[0], defaults={"name": mapping[1]}
            )
            defaults.update(
                canonical_market=canonical,
                reconciliation_status="RESOLVED",
                reason="GOVERNED_MAPPING",
            )
        OddsMarketCanonicalRef.objects.update_or_create(
            market=market, defaults=defaults
        )


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0011_shared_model_readiness"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanonicalBookmaker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=250)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="CanonicalOddsMarket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=250)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="BookmakerCanonicalRef",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "reconciliation_status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("RESOLVED", "Resolved")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "mapping_version",
                    models.CharField(default="fs013-governed-v1", max_length=80),
                ),
                ("reason", models.CharField(blank=True, max_length=120)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "bookmaker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canonical_ref",
                        to="football.bookmaker",
                    ),
                ),
                (
                    "canonical_bookmaker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raw_refs",
                        to="football.canonicalbookmaker",
                    ),
                ),
            ],
            options={
                "ordering": ("bookmaker__source__code", "bookmaker__external_id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("reconciliation_status", "RESOLVED"), _negated=True
                            ),
                            ("canonical_bookmaker__isnull", False),
                            _connector="OR",
                        ),
                        name="football_bookmaker_ref_resolved_has_canonical",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OddsMarketCanonicalRef",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "reconciliation_status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("RESOLVED", "Resolved")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "mapping_version",
                    models.CharField(default="fs013-governed-v1", max_length=80),
                ),
                ("reason", models.CharField(blank=True, max_length=120)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "canonical_market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="raw_refs",
                        to="football.canonicaloddsmarket",
                    ),
                ),
                (
                    "market",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canonical_ref",
                        to="football.oddsmarket",
                    ),
                ),
            ],
            options={
                "ordering": ("market__source__code", "market__external_id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("reconciliation_status", "RESOLVED"), _negated=True
                            ),
                            ("canonical_market__isnull", False),
                            _connector="OR",
                        ),
                        name="football_market_ref_resolved_has_canonical",
                    )
                ],
            },
        ),
        migrations.RunPython(
            seed_governed_market_identities, migrations.RunPython.noop
        ),
    ]
