# Generated by Django 2.1.5 on 2019-01-13 23:06

from django.db import migrations


def states(apps, schema_editor):
    Match = apps.get_model('football', 'Match')
    MATCH_STATES = {
        '0': 'new',
        '1': 'used',
        '2': 'playing',
        '3': 'local',
        '4': 'parity',
        '5': 'visitor',
        '6': 'unknow',
        '8': 'not used'
    }
    for match in Match.objects.all():
        try:
            match.state = MATCH_STATES[match.state]
            match.save()
        except KeyError:
            pass


def states_back(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0011_auto_20190113_0022'),
    ]

    operations = [
        migrations.RunPython(states, states_back),
    ]
