# Generated by Django 2.1.5 on 2019-02-11 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0012_auto_20190113_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'match', 'verbose_name_plural': 'matches'},
        ),
        migrations.RemoveField(
            model_name='match',
            name='ent_datetime',
        ),
        migrations.RemoveField(
            model_name='team',
            name='factor',
        ),
    ]
