# Generated by Django 5.2.17 on 2026-09-11 21:48

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0012_fs013_market_consensus_identity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancerun",
            name="capability",
            field=models.CharField(
                choices=[
                    ("CATALOGUE", "Catalogue"),
                    ("SEASON_BOOTSTRAP", "Season bootstrap"),
                    ("HISTORICAL_BOOTSTRAP", "Historical bootstrap"),
                    ("HISTORICAL_MARKET_BOOTSTRAP", "Historical market bootstrap"),
                    ("WEEKLY_EVALUATION", "Weekly evaluation"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalMarketCoverage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_ATTEMPTED", "Not attempted"),
                            ("RUNNING", "Running"),
                            ("COMPLETE", "Complete"),
                            ("PARTIAL", "Partial"),
                            ("UNSUPPORTED_SOURCE", "Unsupported source"),
                            ("FAILED", "Failed"),
                        ],
                        default="NOT_ATTEMPTED",
                        max_length=30,
                    ),
                ),
                (
                    "strategy_version",
                    models.CharField(default="fs015-v1", max_length=80),
                ),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("source_file", models.CharField(blank=True, max_length=500)),
                ("source_file_checksum", models.CharField(blank=True, max_length=64)),
                ("attempted", models.BooleanField(default=False)),
                ("available", models.BooleanField(default=False)),
                ("source_rows", models.PositiveIntegerField(default=0)),
                ("valid_rows", models.PositiveIntegerField(default=0)),
                ("complete_triplet_rows", models.PositiveIntegerField(default=0)),
                ("imported_rows", models.PositiveIntegerField(default=0)),
                ("unavailable_rows", models.PositiveIntegerField(default=0)),
                ("outside_canonical_pool_rows", models.PositiveIntegerField(default=0)),
                ("unresolved_rows", models.PositiveIntegerField(default=0)),
                ("conflict_rows", models.PositiveIntegerField(default=0)),
                ("invalid_rows", models.PositiveIntegerField(default=0)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("time_semantics", models.JSONField(blank=True, default=list)),
                ("diagnostics", models.JSONField(blank=True, default=dict)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_market_coverages",
                        to="football.competition",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_market_coverages",
                        to="football.season",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historical_market_coverages",
                        to="football.source",
                    ),
                ),
            ],
            options={
                "ordering": ("competition_id", "season__year", "source_id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("competition", "season", "source"),
                        name="football_historical_market_coverage_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("season__isnull", False)),
                        name="football_historical_market_coverage_has_season",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalMarketEvidence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("home_price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("draw_price", models.DecimalField(decimal_places=4, max_digits=10)),
                ("away_price", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "selected_group",
                    models.CharField(
                        choices=[
                            ("PINNACLE_CLOSING", "Pinnacle closing"),
                            ("BET365_CLOSING", "Bet365 closing"),
                            ("AVG_CLOSING", "Average closing"),
                            ("MAX_CLOSING", "Maximum closing"),
                            ("PINNACLE_PRE", "Pinnacle pre"),
                            ("BET365_PRE", "Bet365 pre"),
                            ("AVG_PRE", "Average pre"),
                            ("MAX_PRE", "Maximum pre"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "time_semantics",
                    models.CharField(
                        choices=[
                            ("ASSUMED_T30M", "Assumed T-30m"),
                            ("ASSUMED_T6H", "Assumed T-6h"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_price_is_real", models.BooleanField(default=True)),
                ("timestamp_is_imputed", models.BooleanField(default=True)),
                (
                    "evidence_class",
                    models.CharField(
                        default="SYNTHETIC_TIME_RESEARCH_ONLY", max_length=40
                    ),
                ),
                ("source_competition", models.CharField(max_length=150)),
                ("source_season", models.CharField(max_length=40)),
                ("source_file", models.CharField(max_length=500)),
                ("source_file_checksum", models.CharField(max_length=64)),
                ("source_row_identity", models.CharField(max_length=150)),
                (
                    "provenance_version",
                    models.CharField(default="fs015-v1", max_length=80),
                ),
                (
                    "ingested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_market_evidence",
                        to="football.match",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historical_market_evidence",
                        to="football.source",
                    ),
                ),
            ],
            options={
                "ordering": ("match_id", "source_id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match", "source"),
                        name="football_historical_1x2_match_source_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("home_price__gt", 1),
                            ("draw_price__gt", 1),
                            ("away_price__gt", 1),
                        ),
                        name="football_historical_1x2_prices_gt_one",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("source_price_is_real", True)),
                        name="football_historical_1x2_real_price",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("timestamp_is_imputed", True)),
                        name="football_historical_1x2_imputed_time",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("evidence_class", "SYNTHETIC_TIME_RESEARCH_ONLY")
                        ),
                        name="football_historical_1x2_research_only",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalMarketUnavailable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("SOURCE_NO_COMPLETE_1X2", "Source has no complete 1X2")
                        ],
                        max_length=40,
                    ),
                ),
                ("source_file", models.CharField(max_length=500)),
                ("source_file_checksum", models.CharField(max_length=64)),
                ("source_row_identity", models.CharField(max_length=150)),
                (
                    "provenance_version",
                    models.CharField(default="fs015-v1", max_length=80),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_market_unavailable",
                        to="football.match",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historical_market_unavailable",
                        to="football.source",
                    ),
                ),
            ],
            options={
                "ordering": ("match_id", "source_id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("match", "source"),
                        name="football_historical_1x2_unavailable_unique",
                    )
                ],
            },
        ),
    ]
