# Generated by Django 2.1.5 on 2019-02-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0013_auto_20190210_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='state',
            field=models.CharField(choices=[('N', 'new'), ('U', 'used'), ('P', 'playing'), ('L', 'local'), ('R', 'parity'), ('V', 'visitor'), ('K', 'unknow'), ('T', 'not used')], default='N', max_length=1),
        ),
    ]
