# Generated by Django 5.2.17 on 2026-09-15 04:06

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0013_alter_maintenancerun_capability_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapitalExecutionBasis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("decision_policy_code", models.CharField(max_length=30)),
                (
                    "decision_policy_variant",
                    models.CharField(blank=True, max_length=30),
                ),
                ("decision_policy_version", models.CharField(max_length=100)),
                ("decision_policy_config", models.JSONField(blank=True, default=dict)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("HOME", "Home"),
                            ("DRAW", "Draw"),
                            ("AWAY", "Away"),
                            ("NO_BET", "No bet"),
                        ],
                        max_length=6,
                    ),
                ),
                ("reason", models.CharField(max_length=120)),
                (
                    "model_probability",
                    models.DecimalField(
                        blank=True, decimal_places=12, max_digits=18, null=True
                    ),
                ),
                (
                    "selected_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "expected_value",
                    models.DecimalField(
                        blank=True, decimal_places=12, max_digits=18, null=True
                    ),
                ),
                ("execution_at", models.DateTimeField()),
                ("evidence_not_before", models.DateTimeField()),
                ("evidence_cutoff", models.DateTimeField()),
                (
                    "evidence_class",
                    models.CharField(default="PROSPECTIVE_ACTUAL", max_length=50),
                ),
                ("provenance", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "capture_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_execution_bases",
                        to="football.capturerun",
                    ),
                ),
                (
                    "capture_work_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_execution_bases",
                        to="football.captureworkitem",
                    ),
                ),
                (
                    "historical_market_evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_execution_bases",
                        to="football.historicalmarketevidence",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_execution_bases",
                        to="football.match",
                    ),
                ),
                (
                    "originating_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_execution_bases",
                        to="football.decision",
                    ),
                ),
                (
                    "prediction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_execution_bases",
                        to="football.prediction",
                    ),
                ),
                (
                    "selected_odds_observation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_execution_bases",
                        to="football.oddsobservation",
                    ),
                ),
            ],
            options={
                "ordering": ("execution_at", "match_id", "config_id"),
            },
        ),
        migrations.CreateModel(
            name="CapitalResultObservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_short", models.CharField(max_length=10)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[("HOME", "Home"), ("DRAW", "Draw"), ("AWAY", "Away")],
                        max_length=4,
                    ),
                ),
                ("result_known_at", models.DateTimeField()),
                ("provider_observed_at", models.DateTimeField(blank=True, null=True)),
                ("provenance", models.JSONField(blank=True, default=dict)),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_result_observation",
                        to="football.match",
                    ),
                ),
                (
                    "match_source_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_result_observations",
                        to="football.matchsourceref",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_result_observations",
                        to="football.source",
                    ),
                ),
            ],
            options={
                "ordering": ("result_known_at", "match_id"),
            },
        ),
        migrations.CreateModel(
            name="CapitalRuntimeConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("identity", models.CharField(max_length=180, unique=True)),
                ("runtime_version", models.CharField(max_length=50)),
                ("execution_version", models.CharField(max_length=50)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("CURRENT", "Current prospective"),
                            ("REPLAY", "Replay study"),
                            ("MONTE_CARLO", "Monte Carlo study"),
                            ("STRESS", "Stress study"),
                            ("HISTORICAL", "Historical study"),
                        ],
                        max_length=20,
                    ),
                ),
                ("automatic", models.BooleanField(default=False)),
                ("current", models.BooleanField(default=False)),
                ("source_model_code", models.CharField(max_length=30)),
                ("decision_policy_code", models.CharField(max_length=30)),
                (
                    "decision_policy_variant",
                    models.CharField(blank=True, max_length=30),
                ),
                ("policy_code", models.CharField(max_length=40)),
                ("policy_version", models.CharField(max_length=100)),
                ("policy_config", models.JSONField(default=dict)),
                ("max_lanes", models.PositiveSmallIntegerField()),
                (
                    "initial_bankroll",
                    models.DecimalField(decimal_places=8, max_digits=24),
                ),
                (
                    "bankroll_equity",
                    models.DecimalField(decimal_places=8, max_digits=24),
                ),
                (
                    "reserved_exposure",
                    models.DecimalField(decimal_places=8, default=0, max_digits=24),
                ),
                ("policy_state", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("TERMINATED", "Terminated"),
                            ("COMPLETE", "Complete"),
                            ("DEGRADED", "Degraded"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("practical_ruin", models.BooleanField(default=False)),
                ("termination_reason", models.CharField(blank=True, max_length=120)),
                ("peak_equity", models.DecimalField(decimal_places=8, max_digits=24)),
                (
                    "peak_reserved_exposure",
                    models.DecimalField(decimal_places=8, default=0, max_digits=24),
                ),
                (
                    "maximum_drawdown",
                    models.DecimalField(decimal_places=12, default=0, max_digits=18),
                ),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("provenance", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("automatic", "policy_code", "id"),
                "indexes": [
                    models.Index(
                        fields=["automatic", "current", "status"],
                        name="football_cap_v2_current_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("initial_bankroll__gt", 0)),
                        name="football_capital_v2_initial_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("max_lanes__gt", 0)),
                        name="football_capital_v2_lanes_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reserved_exposure__gte", 0)),
                        name="football_capital_v2_reserved_nonnegative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CapitalPosition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("SETTLED_WIN", "Settled win"),
                            ("SETTLED_LOSS", "Settled loss"),
                            ("VOID", "Void"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("placed_at", models.DateTimeField()),
                ("result_known_at", models.DateTimeField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_stake",
                    models.DecimalField(decimal_places=8, max_digits=24),
                ),
                ("applied_stake", models.DecimalField(decimal_places=8, max_digits=24)),
                ("policy_step", models.PositiveIntegerField(blank=True, null=True)),
                ("request_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "placement_equity_before",
                    models.DecimalField(decimal_places=8, max_digits=24),
                ),
                (
                    "placement_reserved_before",
                    models.DecimalField(decimal_places=8, max_digits=24),
                ),
                (
                    "placement_available_before",
                    models.DecimalField(decimal_places=8, max_digits=24),
                ),
                (
                    "placement_equity_after",
                    models.DecimalField(decimal_places=8, max_digits=24),
                ),
                (
                    "placement_reserved_after",
                    models.DecimalField(decimal_places=8, max_digits=24),
                ),
                (
                    "placement_available_after",
                    models.DecimalField(decimal_places=8, max_digits=24),
                ),
                (
                    "settlement_equity_after",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=24, null=True
                    ),
                ),
                (
                    "settlement_reserved_after",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=24, null=True
                    ),
                ),
                (
                    "settlement_available_after",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=24, null=True
                    ),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=24),
                ),
                ("policy_state_before", models.JSONField(blank=True, default=dict)),
                ("policy_state_after", models.JSONField(blank=True, default=dict)),
                ("cap_hit", models.BooleanField(default=False)),
                (
                    "shortfall",
                    models.DecimalField(decimal_places=8, default=0, max_digits=24),
                ),
                ("practical_ruin", models.BooleanField(default=False)),
                ("termination_reason", models.CharField(blank=True, max_length=120)),
                (
                    "debt_status",
                    models.CharField(
                        choices=[
                            ("CURRENT", "Current"),
                            ("OVERDUE", "Overdue"),
                            ("DEGRADED", "Degraded"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="CURRENT",
                        max_length=20,
                    ),
                ),
                (
                    "result_refresh_attempted_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("result_refresh_error", models.CharField(blank=True, max_length=500)),
                (
                    "execution_basis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="position",
                        to="football.capitalexecutionbasis",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_positions",
                        to="football.match",
                    ),
                ),
                (
                    "result_observation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="football.capitalresultobservation",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="football.capitalruntimeconfig",
                    ),
                ),
            ],
            options={
                "ordering": ("placed_at", "match_id", "config_id"),
            },
        ),
        migrations.CreateModel(
            name="CapitalExecutionState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending execution event"),
                            ("PLACED", "Placed"),
                            ("NOT_PLACED", "Terminal without position"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "non_placement_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NO_BET", "No bet"),
                            (
                                "UNAVAILABLE_NO_DECISION_AT_EXECUTION",
                                "No execution Decision",
                            ),
                            ("NO_EXECUTION_PRICE", "No execution price"),
                            ("MISSED_EXECUTION_WINDOW", "Missed execution window"),
                            ("EXPIRED_CAPACITY", "Capacity expired"),
                            (
                                "INSUFFICIENT_AVAILABLE_CASH",
                                "Insufficient available cash",
                            ),
                            ("INELIGIBLE", "Ineligible"),
                        ],
                        max_length=50,
                    ),
                ),
                ("terminal_at", models.DateTimeField(blank=True, null=True)),
                ("diagnostics", models.JSONField(blank=True, default=dict)),
                (
                    "execution_basis",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_state",
                        to="football.capitalexecutionbasis",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_execution_states",
                        to="football.match",
                    ),
                ),
                (
                    "position",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_state",
                        to="football.capitalposition",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_states",
                        to="football.capitalruntimeconfig",
                    ),
                ),
            ],
            options={
                "ordering": ("match__kickoff", "match_id", "config_id"),
            },
        ),
        migrations.AddField(
            model_name="capitalexecutionbasis",
            name="config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="execution_bases",
                to="football.capitalruntimeconfig",
            ),
        ),
        migrations.AddIndex(
            model_name="capitalposition",
            index=models.Index(
                fields=["status", "debt_status", "placed_at"],
                name="football_cap_v2_debt_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="capitalposition",
            constraint=models.UniqueConstraint(
                fields=("config", "match"),
                name="football_capital_v2_position_config_match_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="capitalposition",
            constraint=models.CheckConstraint(
                condition=models.Q(("requested_stake__gte", 0)),
                name="football_capital_v2_requested_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="capitalposition",
            constraint=models.CheckConstraint(
                condition=models.Q(("applied_stake__gt", 0)),
                name="football_capital_v2_applied_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="capitalexecutionstate",
            constraint=models.UniqueConstraint(
                fields=("config", "match"),
                name="football_capital_v2_state_config_match_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="capitalexecutionbasis",
            constraint=models.UniqueConstraint(
                fields=("config", "match"),
                name="football_capital_v2_basis_config_match_unique",
            ),
        ),
    ]
