# Generated by Django 2.1.5 on 2019-03-18 00:49

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0014_auto_20190218_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
