# Generated by Django 5.2.17 on 2026-09-27 18:53

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0015_fs017_runtime_continuity"),
    ]

    operations = [
        migrations.AddField(
            model_name="capitalruntimeconfig",
            name="entry_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="capitalexecutionstate",
            name="non_placement_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NO_BET", "No bet"),
                    ("STRATEGY_DRAINING", "Strategy draining"),
                    ("STRATEGY_STOPPED", "Strategy stopped"),
                    ("PRE_GLOBAL", "Before activation"),
                    ("INPUT_QUOTES_MISSING", "Missing coherent live quotes"),
                    ("INELEGIBLE_EXECUTION_QUOTE", "Ineligible execution quote"),
                    ("AUTHORITY_EVIDENCE_MISMATCH", "Authority evidence mismatch"),
                    ("EXECUTION_PRICE_MISMATCH", "Execution price mismatch"),
                    (
                        "AWAITING_FINAL_OPEN_SETTLEMENT",
                        "Awaiting final OPEN settlement",
                    ),
                    ("OPERATIONAL_DEPLETION", "Operational depletion"),
                    ("UNAVAILABLE_NO_DECISION_AT_EXECUTION", "No execution Decision"),
                    ("NO_EXECUTION_PRICE", "No execution price"),
                    ("MISSED_EXECUTION_WINDOW", "Missed execution window"),
                    ("EXPIRED_CAPACITY", "Capacity expired"),
                    ("INSUFFICIENT_AVAILABLE_CASH", "Insufficient available cash"),
                    ("INELIGIBLE", "Ineligible"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="CapitalDeployment",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("selection", models.JSONField(default=dict)),
                ("mode", models.CharField(default="SIMULATION_ONLY", max_length=50)),
                ("real_betting", models.BooleanField(default=False)),
                ("state", models.CharField(default="OLD_ACTIVE", max_length=40)),
                ("entry_enabled", models.BooleanField(default=False)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("cutover_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("retiring_config_ids", models.JSONField(default=list)),
                ("successor_mode", models.CharField(blank=True, max_length=60)),
                ("depletion_state", models.CharField(default="ACTIVE", max_length=40)),
                (
                    "depletion_floor",
                    models.DecimalField(decimal_places=8, default=5, max_digits=24),
                ),
                (
                    "config",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="football.capitalruntimeconfig",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CapitalDeploymentEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateTimeField()),
                ("state", models.CharField(max_length=40)),
                ("reason", models.CharField(max_length=120)),
                ("evidence", models.JSONField(default=dict)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="football.capitaldeployment",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="capitaldeployment",
            constraint=models.CheckConstraint(
                condition=models.Q(("id", 1)), name="football_deployment_singleton"
            ),
        ),
        migrations.AddConstraint(
            model_name="capitaldeployment",
            constraint=models.CheckConstraint(
                condition=models.Q(("real_betting", False)),
                name="football_deployment_simulated",
            ),
        ),
        migrations.AddConstraint(
            model_name="capitaldeployment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("entry_enabled", False),
                    models.Q(
                        ("activated_at__isnull", False),
                        ("config__isnull", False),
                        ("state", "ACTIVE"),
                    ),
                    _connector="OR",
                ),
                name="football_deployment_admission_active",
            ),
        ),
    ]
