# Generated by Django 2.1.5 on 2019-03-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0015_auto_20190318_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='state',
            field=models.CharField(choices=[('N', 'new'), ('U', 'used'), ('P', 'playing'), ('L', 'local'), ('R', 'parity'), ('V', 'visitor'), ('T', 'not used')], default='N', max_length=1),
        ),
    ]
