# Generated by Django 2.1.5 on 2019-03-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0016_auto_20190326_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguerelatedname',
            name='related_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
