# Generated by Django 5.2.17 on 2026-09-30 00:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0017_fs022_live_evaluation_recovery"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyBinding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("candidate_id", models.PositiveSmallIntegerField()),
                ("contract", models.JSONField()),
                (
                    "digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="BSDEventBinding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bsd_league_id", models.PositiveIntegerField()),
                ("bsd_event_id", models.PositiveIntegerField(unique=True)),
                ("bound_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("provenance", models.JSONField(default=dict)),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bsd_event",
                        to="football.match",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompetitionResultRoute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_football_league_id", models.PositiveIntegerField()),
                ("bsd_league_ids", models.JSONField(default=list)),
                (
                    "bsd_state",
                    models.CharField(default="BSD_BOOTSTRAP_PENDING", max_length=40),
                ),
                (
                    "season_state",
                    models.CharField(default="TEMPORARILY_UNAVAILABLE", max_length=40),
                ),
                ("season_id", models.PositiveIntegerField(blank=True, null=True)),
                ("season_checked_at", models.DateTimeField(blank=True, null=True)),
                ("bsd_backoff_until", models.DateTimeField(blank=True, null=True)),
                ("bsd_failures", models.PositiveSmallIntegerField(default=0)),
                (
                    "bsd_failure_window_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("provenance", models.JSONField(default=dict)),
                (
                    "competition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result_route",
                        to="football.competition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StrategyEpoch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DRAINING", "Draining"),
                            ("DRAINED", "Drained"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "initial_bankroll",
                    models.DecimalField(decimal_places=8, max_digits=24),
                ),
                ("activated_at", models.DateTimeField()),
                ("drained_at", models.DateTimeField(blank=True, null=True)),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="epochs",
                        to="football.strategybinding",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="capitaldeployment",
            name="active_epoch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deployments",
                to="football.strategyepoch",
            ),
        ),
        migrations.AddField(
            model_name="capitalruntimeconfig",
            name="strategy_epoch",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runtime_config",
                to="football.strategyepoch",
            ),
        ),
        migrations.CreateModel(
            name="StrategySwitch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initial_bankroll",
                    models.DecimalField(decimal_places=8, max_digits=24),
                ),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_epoch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="switches",
                        to="football.strategyepoch",
                    ),
                ),
                (
                    "target_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="football.strategybinding",
                    ),
                ),
                (
                    "target_epoch",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="originating_switch",
                        to="football.strategyepoch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BSDTeamMapping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bsd_team_id", models.PositiveIntegerField()),
                ("bsd_league_id", models.PositiveIntegerField()),
                ("approval", models.CharField(max_length=30)),
                ("provenance", models.JSONField(default=dict)),
                (
                    "canonical_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="football.team"
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="teams",
                        to="football.competitionresultroute",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("route", "canonical_team", "bsd_league_id"),
                        name="bsd_canonical_team_unique",
                    ),
                    models.UniqueConstraint(
                        fields=("bsd_league_id", "bsd_team_id"),
                        name="bsd_provider_team_unique",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ResultProviderObservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=30)),
                ("external_ref", models.CharField(max_length=100)),
                ("provider_observed_at", models.DateTimeField()),
                ("result_known_at", models.DateTimeField()),
                ("status_short", models.CharField(max_length=20)),
                ("home_regulation", models.SmallIntegerField(blank=True, null=True)),
                ("away_regulation", models.SmallIntegerField(blank=True, null=True)),
                ("outcome", models.CharField(blank=True, max_length=4)),
                ("authoritative", models.BooleanField(default=False)),
                ("conflict", models.BooleanField(default=False)),
                ("fallback_reason", models.CharField(blank=True, max_length=100)),
                ("provenance", models.JSONField(default=dict)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_results",
                        to="football.match",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "match",
                            "provider",
                            "external_ref",
                            "provider_observed_at",
                        ),
                        name="result_provider_observation_unique",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="strategyepoch",
            constraint=models.CheckConstraint(
                condition=models.Q(("initial_bankroll__gt", 0)),
                name="strategy_epoch_positive_bankroll",
            ),
        ),
        migrations.AddConstraint(
            model_name="strategyswitch",
            constraint=models.UniqueConstraint(
                fields=("source_epoch", "target_binding", "initial_bankroll"),
                name="strategy_switch_restart_key_unique",
            ),
        ),
    ]
