# Generated by Django 2.1.5 on 2019-04-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0017_auto_20190326_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='parity_factor',
            new_name='draw_factor',
        ),
        migrations.AlterField(
            model_name='match',
            name='state',
            field=models.CharField(choices=[('N', 'new'), ('U', 'used'), ('P', 'playing'), ('L', 'local'), ('R', 'draw'), ('V', 'visitor'), ('T', 'not used')], default='N', max_length=1),
        ),
    ]
