# Generated by Django 2.1.5 on 2019-04-07 18:53

from django.db import migrations


def delete_leagues(apps, schema_editor):
    league_model = apps.get_model('football', 'League')
    league_related_model = apps.get_model('football', 'LeagueRelatedName')
    league_model.objects.all().delete()
    league_related_model.objects.all().delete()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0018_auto_20190401_2032'),
    ]

    operations = [
        migrations.RunPython(delete_leagues, reverse),
    ]
