# Generated by Django 2.1.5 on 2019-04-07 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190310_1143'),
        ('football', '0019_data_delete_leagues_20190407_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguerelatedname',
            name='related_name',
        ),
        migrations.AddField(
            model_name='league',
            name='draw_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaguerelatedname',
            name='bet_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.BetPage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaguerelatedname',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='local_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='visitor_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
