# Generated by Django 5.2.17 on 2026-09-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football", "0019_fs023_live_binding_backfill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captureworkitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned"),
                    ("NOT_DUE", "Not due"),
                    ("ALREADY_FULFILLED", "Already fulfilled"),
                    ("STATUS_INELIGIBLE", "Status ineligible"),
                    ("ODDS_NOT_COVERED", "Odds not covered"),
                    ("UNRESOLVED_IDENTITY", "Unresolved identity"),
                    ("QUOTA_RESERVE", "Quota reserve"),
                    (
                        "INSUFFICIENT_WORST_CASE_BUDGET",
                        "Insufficient worst-case budget",
                    ),
                    ("MISSED_WINDOW", "Missed window"),
                    ("MISSED_STRATEGY_WINDOW", "Missed T10 due only to quota"),
                    ("LATE_CAPTURE", "Late capture"),
                    ("PROVIDER_BACKOFF", "Provider backoff"),
                    ("CONCURRENT_EXECUTOR", "Concurrent executor"),
                    ("SUCCESS", "Success"),
                    ("SUCCESS_EMPTY", "Success empty"),
                    ("PARTIAL_PAGINATION", "Partial pagination"),
                    ("FAILED_PROVIDER", "Provider failed"),
                ],
                default="PLANNED",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="providercallaudit",
            name="capability",
            field=models.CharField(
                choices=[
                    ("DAILY_FIXTURE_DISCOVERY", "Daily fixture discovery"),
                    ("ODDS_T10", "Odds T-10"),
                    ("ODDS_T30", "Odds T-30"),
                    ("ODDS_T60", "Odds T-60"),
                    ("ODDS_T6H", "Odds T-6h"),
                    ("OPEN_RESULT_BATCH", "Open result batch"),
                    ("NONBET_RESULT_BATCH", "Non-bet result batch"),
                    (
                        "CATALOGUE_OR_SEASON_MAINTENANCE",
                        "Catalogue or season maintenance",
                    ),
                    ("OTHER_EXPLICIT_MAINTENANCE", "Other explicit maintenance"),
                    ("FUTURE_EXECUTION_QUOTE", "Future execution quote"),
                ],
                max_length=50,
            ),
        ),
    ]
