# Generated by Django 2.1.5 on 2019-04-29 18:16

from django.db import migrations


def add_inkabet_leagues(apps, schema_editor):
    league_map = (
        ('Serie A', 'BR', 'BRASIL - SERIE A'),
        ('Premier League', 'KZ', 'KAZAKHSTAN PREMIER LEAGUE'),
        ('Serie B', 'BR', 'BRAZIL SERIE B'),
        ('Pro League', 'IR', 'IRÁN PRO LIGA'),
    )
    LeagueRelatedName = apps.get_model('football', 'LeagueRelatedName')
    BetPage = apps.get_model('accounts', 'BetPage')
    League = apps.get_model('football', 'League')
    inkabet = BetPage.objects.get(name__icontains='inkabet')
    for league in league_map:
        league_obj = League.objects.get(name=league[0], country=league[1])
        LeagueRelatedName.objects.update_or_create(
            league=league_obj,
            bet_page=inkabet,
            defaults={'name': league[2]}
        )


def remove_inkabet_leagues(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0021_auto_20190413_1545'),
    ]

    operations = [
        migrations.RunPython(add_inkabet_leagues, remove_inkabet_leagues),
    ]
