# Generated by Django 2.2.4 on 2019-10-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0023_data_leagues_20190520_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='inkabet_url',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
