# Generated by Django 2.1 on 2018-09-05 22:37

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', fernet_fields.fields.EncryptedCharField(max_length=32)),
                ('minimum_bet', models.IntegerField()),
                ('funds', models.FloatField()),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='BetPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('domain', models.URLField()),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Bet Page',
                'verbose_name_plural': 'Bet Pages',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='bet_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.BetPage'),
        ),
    ]
