# Generated by Django 5.2.2 on 2025-07-23 03:30

import django.db.models.deletion
import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BetPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("domain", models.URLField()),
                ("active", models.BooleanField()),
            ],
            options={
                "verbose_name": "Bet Page",
                "verbose_name_plural": "Bet Pages",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=64)),
                ("password", fernet_fields.fields.EncryptedCharField(max_length=32)),
                ("email", models.EmailField(max_length=254)),
                ("num_allow_tables", models.IntegerField(default=1)),
                ("start_bet", models.IntegerField()),
                (
                    "bet_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.betpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
            },
        ),
    ]
