# Generated by Django 2.1 on 2018-09-10 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_auto_20180828_1639'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favorite_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football.Team'),
        ),
        migrations.AddField(
            model_name='account',
            name='max_favorite_bet',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='account',
            name='min_favorite_bet',
            field=models.FloatField(default=2),
        ),
    ]
