# Generated by Django 2.1 on 2018-09-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180910_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='account',
            name='funds',
            field=models.FloatField(default=0.0),
        ),
    ]
