# Generated by Django 2.1 on 2018-09-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180913_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='num_allow_tables',
            field=models.IntegerField(default=1),
        ),
    ]
