# Generated by Django 2.1 on 2018-09-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_num_allow_tables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='profit',
            new_name='profit_to_tables',
        ),
    ]
