# Generated by Django 2.1 on 2018-09-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180914_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profit_to_tables_index',
            field=models.FloatField(default=0.0),
        ),
    ]
