# Generated by Django 2.1 on 2018-12-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_profit_to_tables_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='betpage',
            name='match_list_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
