# Generated by Django 2.1.5 on 2019-01-12 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_betpage_match_list_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='favorite_team',
        ),
        migrations.RemoveField(
            model_name='account',
            name='max_favorite_bet',
        ),
        migrations.RemoveField(
            model_name='account',
            name='min_favorite_bet',
        ),
    ]
