# Generated by Django 2.1.5 on 2019-03-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190112_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='minimum_bet',
            new_name='start_bet',
        ),
        migrations.RemoveField(
            model_name='account',
            name='profit_to_tables',
        ),
        migrations.RemoveField(
            model_name='account',
            name='profit_to_tables_index',
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
