# Generated by Django 2.2.4 on 2019-10-23 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190310_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betpage',
            name='match_list_url',
        ),
    ]
