# Generated by Django 2.2.4 on 2019-11-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_betpage_match_list_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='funds',
        ),
    ]
