from django.core.management.base import BaseCommand

from django_countries import countries

from accounts.models import BetPage
from football.models import League, LeagueRelatedName


# Para obtener la lista de ligas
def get_missing():
    for l in League.objects.all().order_by("country"):
        if not l.leaguerelatedname_set.all().exists():
            print("('%s', '%s', '%s', '%s')," % (
                l.name, l.country, countries.name(l.country), "?"))
        else:
            print("('%s', '%s', '%s', '%s')," % (
                l.name, l.country, countries.name(l.country),
                l.leaguerelatedname_set.last().name))


class Command(BaseCommand):
    help = 'Update or create matches'

    def handle(self, *args, **options):
        league_map = (
            ('Arabian Gulf League', 'AE', 'United Arab Emirates', 'UAE ARABIAN GULF LEAGUE'),
            ('Super Liga', 'AL', 'Albania', 'ALBANIA SUPERLIGA'),
            ('Premier League', 'AM', 'Armenia', 'ARMENIA PREMIER LEAGUE'),
            ('Primera B Nacional', 'AR', 'Argentina', 'ARGENTINA NATIONAL B DIVISION'),
            ('Primera B Metropolitana', 'AR', 'Argentina', 'ARGENTINA PRIMERA B METROPOLITANA'),
            ('Primera', 'AR', 'Argentina', 'ARGENTINA SUPERLIGA CUP'),
            ('2. Liga', 'AT', 'Austria', 'AUSTRIA 2. LIGA'),
            ('Bundesliga', 'AT', 'Austria', 'AUSTRIA BUNDESLIGA'),
            ('Regionalliga Ost', 'AT', 'Austria', 'AUSTRIA REGIONALLIGA EAST'),
            ('A-League', 'AU', 'Australia', 'A-LEAGUE'),
            ('Premyer Liqa', 'AZ', 'Azerbaijan', 'AZERBAIJAN - PREMIER LEAGUE'),
            ('Premier Liga', 'BA', 'Bosnia-Herzegovina', 'BOSNIA-HERZEGOVINA PREMIER LIGA'),
            ('First Division B', 'BE', 'Belgium', 'FIRST DIVISION B'),
            ('First Division A', 'BE', 'Belgium', 'FIRST DIVISION A'),
            ('First League', 'BG', 'Bulgaria', 'BULGARIA FIRST DIVISION'),
            ('Premier League', 'BH', 'Bahrain', 'BARÉIN - PREMIER LEAGUE'),
            ('LFPB', 'BO', 'Bolivia', 'PRIMERA DIVISIÓN'),
            ('Campeonato Carioca', 'BR', 'Brazil', 'CARIOCA'),
            ('Campeonato Paulista A1', 'BR', 'Brazil', 'PAULISTA A1'),
            ('Campeonato Baiano', 'BR', 'Brazil', 'BAIANO'),
            ('Serie A', 'BR', 'Brazil', 'BRASIL - SERIE A'),
            ('Campeonato Paranaense', 'BR', 'Brazil', 'PARANAENSE'),
            ('Campeonato Mineiro', 'BR', 'Brazil', 'MINEIRO'),
            ('Campeonato Pernambucano', 'BR', 'Brazil', 'PERNAMBUCANO'),
            ('Campeonato Cearense', 'BR', 'Brazil', 'CEARENSE'),
            ('Campeonato Paulista A2', 'BR', 'Brazil', 'PAULISTA A2'),
            ('Campeonato Gaucho', 'BR', 'Brazil', 'GAÚCHO'),
            ('Campeonato Catarinense', 'BR', 'Brazil', 'CATARINENSE'),
            ('Campeonato Paulista A3', 'BR', 'Brazil', 'PAULISTA A3'),
            ('Serie C', 'BR', 'Brazil', 'BRAZIL SERIE C'),
            ('Campeonato Goiano', 'BR', 'Brazil', 'GOIANO'),
            ('Serie B', 'BR', 'Brazil', 'BRAZIL SERIE B'),
            ('Div 1', 'BY', 'Belarus', 'BELARUS PREMIER LEAGUE'),
            ('Canadian Premier League', 'CA', 'Canada', ''),
            ('Super League', 'CH', 'Switzerland', 'SUPER LIGA'),
            ('Challenge', 'CH', 'Switzerland', 'SWITZERLAND CHALLENGE LEAGUE'),
            ('Primera B', 'CL', 'Chile', 'CHILE PRIMERA DIVISION B'),
            ('Primera', 'CL', 'Chile', 'CHILE PRIMERA DIVISION'),
            ('Elite One', 'CM', 'Cameroon', 'Cameroon Elite ONE'),
            ('Super League', 'CN', 'China', 'SUPER LIGA'),
            ('League One', 'CN', 'China', 'CHINA LEAGUE ONE'),
            ('Primera A', 'CO', 'Colombia', 'COLOMBIA CATEGORÍA PRIMERA A'),
            ('Primera B', 'CO', 'Colombia', 'COLOMBIA CATEGORÍA PRIMERA B'),
            ('Primera', 'CR', 'Costa Rica', 'COSTA RICA - PRIMERA DIVISIÓN'),
            ('League One', 'CT', 'Scotland', 'LEAGUE ONE'),
            ('Premiership', 'CT', 'Scotland', 'PREMIER LEAGUE'),
            ('League Two', 'CT', 'Scotland', 'LEAGUE TWO'),
            ('Championship', 'CT', 'Scotland', 'SCOTLAND CHAMPIONSHIP'),
            ('Div 1', 'CY', 'Cyprus', 'DIVISIÓN 1'),
            ('FNL', 'CZ', 'Czech Rep.', 'CZECH REPUBLIC SECOND DIVISON'),
            ('First League', 'CZ', 'Czech Rep.', 'CZECH REPUBLIC PREMIER LEAGUE'),
            ('Bundesliga', 'DE', 'Germany', 'BUNDESLIGA'),
            ('Regionalliga North', 'DE', 'Germany', 'GERMANY REGIONALLIGA NORD'),
            ('Regionalliga West', 'DE', 'Germany', 'GERMANY REGIONALLIGA WEST'),
            ('Regionalliga Southwest', 'DE', 'Germany', 'GERMANY REGIONALLIGA SÜDWEST'),
            ('Regionalliga Northeast', 'DE', 'Germany', 'GERMANY REGIONALLIGA NORDOST'),
            ('2. Bundesliga', 'DE', 'Germany', '2.BUNDESLIGA'),
            ('Regionalliga Bavaria', 'DE', 'Germany', 'GERMANY REGIONALLIGA BAYERN'),
            ('Div 3', 'DE', 'Germany', '3.LIGA'),
            ('Div 1', 'DK', 'Denmark', 'DENMARK 1.DIVISION'),
            ('Superliga', 'DK', 'Denmark', 'SUPERLIGA'),
            ('Ligue 1', 'DZ', 'Algeria', 'LIGUE PROFESSIONNELLE 1'),
            ('Serie A', 'EC', 'Ecuador', 'ECUADOR PRIMERA DIVISION'),
            ('Serie B', 'EC', 'Ecuador', 'ECUADOR PRIMERA B'),
            ('Meistriliiga', 'EE', 'Estonia', 'ESTONIA MEISTRILIIGA'),
            ('Premier League', 'EG', 'Egypt', 'PREMIER LEAGUE'),
            ('National League North', 'EN', 'England', 'NATIONAL LEAGUE NORTE'),
            ('National League South', 'EN', 'England', 'NATIONAL LEAGUE SUR'),
            ('League Two', 'EN', 'England', 'LEAGUE 2'),
            ('National League', 'EN', 'England', 'NATIONAL LEAGUE'),
            ('League One', 'EN', 'England', 'LEAGUE 1'),
            ('Championship', 'EN', 'England', 'CHAMPIONSHIP'),
            ('Premier League', 'EN', 'England', 'PREMIER LEAGUE'),
            ('Segunda B Gr. 3', 'ES', 'Spain', 'SEGUNDA B GRUPO 3'),
            ('Segunda B Gr. 4', 'ES', 'Spain', 'SEGUNDA B GRUPO 4'),
            ('Primera', 'ES', 'Spain', 'PRIMERA DIVISIÓN'),
            ('Segunda B Gr. 1', 'ES', 'Spain', 'SEGUNDA B GRUPO 1'),
            ('Segunda', 'ES', 'Spain', 'SEGUNDA DIVISIÓN'),
            ('Segunda B Gr. 2', 'ES', 'Spain', 'SEGUNDA B GRUPO 2'),
            ('Veikkausliiga', 'FI', 'Finland', 'FINLAND VEIKKAUSLIIGA'),
            ('Ykkonen', 'FI', 'Finland', 'FINLAND YKKÖNEN'),
            ('Kakkonen Läntinen', 'FI', 'Finland', 'Finland Kakkonen Läntinen'),
            ('Ligue 1', 'FR', 'France', 'LIGUE 1'),
            ('National', 'FR', 'France', 'Ligue National 2'),
            ('Ligue 2', 'FR', 'France', 'LIGUE 2'),
            ('Erovnuli Liga', 'GE', 'Georgia', 'GEORGIA EROVNULI LIGA'),
            ('Super League', 'GR', 'Greece', 'SUPER LIGA'),
            ('Football League', 'GR', 'Greece', 'FOOTBALL LEAGUE'),
            ('Liga Nacional', 'GT', 'Guatemala', 'GUATEMALA LIGA NACIONAL'),
            ('LNP', 'HN', 'Honduras', 'HONDURAS LIGA NACIONAL DE FÚTBOL'),
            ('1. HNL', 'HR', 'Croatia', 'CROATIA FIRST DIVISION'),
            ('2. HNL', 'HR', 'Croatia', 'CROATIA SECOND DIVISION'),
            ('NB II', 'HU', 'Hungary', 'HUNGARY DIVISION 2'),
            ('Liga 1', 'ID', 'Indonesia', 'Indonesia Liga 1'),
            ('Premier League', 'IE', 'Ireland', 'IRELAND PREMIER DIVISION'),
            ('Div 1', 'IE', 'Ireland', 'LIGUE PROFESSIONNELLE 1'),
            ('Premier League', 'IL', 'Israel', 'LIGAT AL'),
            ('Azadegan League', 'IR', 'Iran', 'IRAN AZADEGAN LEAGUE'),
            ('Pro League', 'IR', 'Iran', 'IRÁN PRO LIGA'),
            ('1. Deild', 'IS', 'Iceland', 'ICELAND SECOND DIVISION'),
            ('Urvalsdeild', 'IS', 'Iceland', 'ICELAND PREMIER LEAGUE'),
            ('Serie B', 'IT', 'Italy', 'SERIE B'),
            ('Serie C Gr. C', 'IT', 'Italy', 'SERIE C GIRONE C'),
            ('Serie C Gr. B', 'IT', 'Italy', 'SERIE C GIRONE B'),
            ('Serie A', 'IT', 'Italy', 'SERIE A'),
            ('Serie C Gr. A', 'IT', 'Italy', 'SERIE C GIRONE A'),
            ('J3 League', 'JP', 'Japan', 'JAPAN J. LEAGUE 3'),
            ('J League', 'JP', 'Japan', 'JAPAN J. LEAGUE'),
            ('J2 League', 'JP', 'Japan', 'JAPAN J. LEAGUE 2'),
            ('Premier League', 'KE', 'Kenya', 'KENIA PREMIER LEAGUE'),
            ('K League 1', 'KR', 'Korea', 'KOREA REPUBLIC K-LEAGUE 1p'),
            ('K League 2', 'KR', 'Korea', 'KOREA REPUBLIC K-LEAGUE 2'),
            ('Premier League', 'KZ', 'Kazakhstan', 'KAZAKHSTAN PREMIER LEAGUE'),
            ('Div 1', 'LT', 'Lithuania', 'A LYGA'),
            ('National Division', 'LU', 'Luxembourg', 'LUXEMBOURG NATIONAL DIVISION'),
            ('Virsliga', 'LV', 'Latvia', 'LATVIA VIRSLIGA'),
            ('Botola Pro', 'MA', 'Morocco', 'MOROCCO BOTOLA'),
            ('National Division', 'MD', 'Moldova', 'Moldova National Division'),
            ('MFL', 'MK', 'Macedonia', 'MACEDONIA 1.LEAGUE'),
            ('Liga MX', 'MX', 'Mexico', 'LIGA MX'),
            ('Ascenso MX', 'MX', 'Mexico', 'LIGA DE ASCENSO'),
            ('Super League', 'MY', 'Malaysia', 'MALAYSIA LIGA SUPER'),
            ('Premiership', 'ND', 'Northern Ireland', 'IRELAND PREMIER DIVISION'),
            ('Eerste Divisie', 'NL', 'Netherlands', 'EERSTE DIVISIE'),
            ('Eredivisie', 'NL', 'Netherlands', 'EREDIVISIE'),
            ('Eliteserien', 'NO', 'Norway', 'NORWAY PREMIER LEAGUE'),
            ('Div 2, Gr. 2', 'NO', 'Norway', 'NORWAY SECOND DIVISION GROUP 2'),
            ('1. Division', 'NO', 'Norway', 'NORWAY FIRST DIVISION'),
            ('Div 2, Gr. 1', 'NO', 'Norway', 'NORWAY SECOND DIVISION GROUP 1'),
            ('Professional League', 'OM', 'Oman', 'Oman Professional League'),
            ('LPF', 'PA', 'Panama', 'PANAMA LIGA DE FÚTBOL'),
            ('Primera', 'PE', 'Peru', 'PERU LIGA 1'),
            ('Div 2', 'PL', 'Poland', 'POLAND SECOND LEAGUE'),
            ('Div 1', 'PL', 'Poland', 'POLAND FIRST LEAGUE'),
            ('Ekstraklasa', 'PL', 'Poland', 'EKSTRAKLASA'),
            ('Segunda', 'PT', 'Portugal', 'SEGUNDA LIGA'),
            ('Primeira', 'PT', 'Portugal', 'PRIMEIRA LIGA'),
            ('Primera', 'PY', 'Paraguay', 'PARAGUAY PRIMERA DIVISION'),
            ('Liga I', 'RO', 'Romania', 'ROMANIA LIGA II'),
            ('Liga II', 'RO', 'Romania', 'LIGA 1'),
            ('SuperLiga', 'RS', 'Serbia', 'SERBIA SUPERLIGA'),
            ('PFL Ural-Povolzhye', 'RU', 'Russia', 'RUSSIA 2. DIVISION URAL-POVOLZHYE'),
            ('Premier League', 'RU', 'Russia', 'RUSSIA PREMIER LEAGUE'),
            ('Saudi Professional League', 'SA', 'Saudi Arabia', 'PRO LEAGUE'),
            ('Div 1 Sodra', 'SE', 'Sweden', 'SWEDEN DIVISION 1 SÖDRA'),
            ('Superettan', 'SE', 'Sweden', 'SWEDEN SUPERETTAN'),
            ('Div 1 Norra', 'SE', 'Sweden', 'SWEDEN DIVISION 1 NORRA'),
            ('Allsvenskan', 'SE', 'Sweden', 'SWEDEN ALLSVENSKAN'),
            ('S-League', 'SG', 'Singapore', 'SINGAPORE PREMIER LEAGUE'),
            ('Div 1', 'SI', 'Slovenia', 'SLOVENIA PRVA LIGA'),
            ('Div 2', 'SK', 'Slovakia', 'SLOVAKIA 2. LIGA'),
            ('Div 1', 'SK', 'Slovakia', 'SLOVAKIA SUPER LIGA'),
            ('Primera Division', 'SV', 'El Salvador', 'PRIMERA DIVISIÓN'),
            ('Thai League 1', 'TH', 'Thailand', 'Thailand League 1'),
            ('Ligue 1', 'TN', 'Tunisia', 'TUNISIA LIGUE 1'),
            ('Div 1', 'TR', 'Turkey', '1. LIGA'),
            ('Super Lig', 'TR', 'Turkey', 'SUPER LIGA'),
            ('Premier League', 'UA', 'Ukraine', 'UKRAINE PREMIER LEAGUE'),
            ('Persha Liga', 'UA', 'Ukraine', 'UKRAINE FIRST LEAGUE'),
            ('Premier League', 'UG', 'Uganda', 'UGANDA PREMIER LEAGUE'),
            ('MLS', 'US', 'USA', 'US MAJOR LEAGUE SOCCER'),
            ('Primera', 'UY', 'Uruguay', 'URUGUAY PRIMERA DIVISIÓN'),
            ('Primera Division', 'VE', 'Venezuela', 'VENEZUELA PRIMERA DIVISION'),
            ('V-League', 'VN', 'Vietnam', 'VIETNAM V.LEAGUE 1'),
            ('PSL', 'ZA', 'South Africa', 'PREMIER SOCCER LEAGUE'),
            ('National First Division', 'ZA', 'South Africa', 'NATIONAL FIRST DIVISION'),
        )
        inkabet = BetPage.objects.get(name__icontains='inkabet')
        for league in league_map:
            league_obj = League.objects.get(name=league[0], country=league[1])
            league, created = LeagueRelatedName.objects.update_or_create(
                league=league_obj,
                bet_page=inkabet,
                defaults={'name': league[3]}
            )
            if created:
                print(league)
