# Generated by Django 5.2.2 on 2025-07-23 03:30

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("football", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BetTable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("total_profit", models.FloatField(default=0)),
                ("total_inversion", models.FloatField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[("A", "available"), ("F", "finished")],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("bucle_number", models.IntegerField(default=0)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BetRow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("bet_amount", models.FloatField(default=0)),
                ("inversion_amount", models.FloatField(default=0)),
                ("profit", models.FloatField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("N", "new"),
                            ("C", "current"),
                            ("W", "won"),
                            ("L", "lost"),
                        ],
                        default="N",
                        max_length=1,
                    ),
                ),
                ("iteration", models.PositiveSmallIntegerField(default=0)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="football.match"
                    ),
                ),
                (
                    "previous",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="previous_data",
                        to="bet.betrow",
                    ),
                ),
                (
                    "bet_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bet_rows",
                        to="bet.bettable",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
