# Generated by Django 2.1 on 2018-08-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettable',
            name='bucle_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bettable',
            name='total_inversion',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bettable',
            name='total_profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='bet_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='inversion_amount',
            field=models.FloatField(default=0),
        ),
    ]
