# Generated by Django 2.1 on 2018-08-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0002_auto_20180820_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatable',
            name='state',
            field=models.IntegerField(choices=[(0, 'new'), (1, 'current'), (2, 'won'), (3, 'lost')], default=0),
        ),
    ]
