# Generated by Django 2.1 on 2018-08-22 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0003_datatable_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatable',
            name='previous',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_data', to='bet.DataTable'),
        ),
    ]
