# Generated by Django 2.1 on 2018-08-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0004_datatable_previous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='state',
            field=models.IntegerField(choices=[(0, 'new'), (1, 'current'), (2, 'won'), (3, 'lost'), (4, 'waiting')], default=0),
        ),
    ]
