# Generated by Django 2.1 on 2018-08-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0005_auto_20180822_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettable',
            name='state_in_time',
            field=models.IntegerField(choices=[(0, 'FT'), (1, 'HT')], default=1),
        ),
        migrations.AddField(
            model_name='datatable',
            name='state_in_time',
            field=models.IntegerField(choices=[(0, 'FT'), (1, 'HT')], default=0),
        ),
    ]
