# Generated by Django 2.1 on 2018-08-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0006_auto_20180829_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettable',
            name='state_in_time',
            field=models.IntegerField(choices=[(0, 'FT'), (1, 'HT')], default=0),
        ),
    ]
