# Generated by Django 2.1 on 2018-09-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0007_auto_20180829_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettable',
            name='state',
            field=models.IntegerField(choices=[(1, 'available'), (2, 'finished'), (4, 'favorite')], default=1),
        ),
    ]
