# Generated by Django 2.1 on 2018-09-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0008_auto_20180912_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettable',
            name='state',
            field=models.IntegerField(choices=[(1, 'available'), (2, 'finished'), (3, 'paused'), (4, 'favorite')], default=1),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='state',
            field=models.IntegerField(choices=[(0, 'new'), (1, 'current'), (2, 'won'), (3, 'lost'), (4, 'waiting'), (5, 'paused')], default=0),
        ),
    ]
