# Generated by Django 2.1 on 2018-09-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0009_auto_20180913_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='state',
            field=models.IntegerField(choices=[(0, 'new'), (1, 'current'), (2, 'won'), (3, 'lost'), (4, 'waiting'), (5, 'paused'), (6, 'current_paused')], default=0),
        ),
    ]
