# Generated by Django 2.1.5 on 2019-01-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0010_auto_20180918_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettable',
            name='state',
            field=models.CharField(choices=[('A', 'available'), ('F', 'finished'), ('P', 'paused')], default='A', max_length=1),
        ),
    ]
