# Generated by Django 2.1.5 on 2019-01-11 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0011_auto_20190111_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bettable',
            name='state_in_time',
        ),
        migrations.RemoveField(
            model_name='datatable',
            name='state_in_time',
        ),
    ]
