# Generated by Django 2.1.5 on 2019-01-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0012_auto_20190111_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettable',
            name='state',
            field=models.CharField(choices=[('A', 'available'), ('F', 'finished')], default='A', max_length=1),
        ),
    ]
