# Generated by Django 2.1.5 on 2019-01-13 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0013_auto_20190112_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_data', to='bet.DataTable'),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='state',
            field=models.CharField(choices=[('N', 'new'), ('C', 'current'), ('W', 'won'), ('L', 'lost'), ('T', 'waiting')], default='N', max_length=1),
        ),
    ]
