# Generated by Django 2.1.5 on 2019-01-13 22:52

from django.db import migrations


def states(apps, schema_editor):
    BetTable = apps.get_model('bet', 'BetTable')
    BET_STATES = {
        "1": 'A',
        "2": 'F'
    }
    for bet_table in BetTable.objects.all():
        try:
            bet_table.state = BET_STATES[bet_table.state]
            bet_table.save()
        except KeyError:
            pass
    DataTable = apps.get_model('bet', 'DataTable')
    DATA_STATES = {
        '0': 'N',
        '1': 'C',
        '2': 'W',
        '3': 'L',
        '4': 'T'
    }
    for data_table in DataTable.objects.all():
        try:
            data_table.state = DATA_STATES[data_table.state]
            data_table.save()
        except KeyError:
            pass


def states_back(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0014_auto_20190113_0022'),
    ]

    operations = [
        migrations.RunPython(states, states_back),
    ]
