# Generated by Django 2.1.5 on 2019-02-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0013_auto_20190210_2207'),
        ('bet', '0015_auto_20190113_1752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataTable',
            new_name='BetRow',
        ),
    ]
