# Generated by Django 2.1.5 on 2019-02-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0016_auto_20190216_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betrow',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
