# Generated by Django 2.1.5 on 2019-03-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0017_auto_20190218_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='betrow',
            name='iteration',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
