# Generated by Django 2.1.5 on 2019-03-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0018_betrow_iteration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betrow',
            name='state',
            field=models.CharField(choices=[('N', 'new'), ('C', 'current'), ('W', 'won'), ('L', 'lost')], default='N', max_length=1),
        ),
    ]
