# Generated by Django 2.1.5 on 2019-03-17 16:02

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0019_auto_20190317_1232'),
    ]

    operations = [
        UnaccentExtension(),
    ]
