# Generated by Django 2.1.5 on 2019-04-13 11:23

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0020_auto_20190317_1602'),
    ]

    operations = [
        TrigramExtension(),
    ]
