# Generated by Django 2.2.4 on 2019-11-20 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0021_auto_20190413_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betrow',
            name='bet_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_rows', to='bet.BetTable'),
        ),
    ]
